### ISSUE TITLE
使用nacos-aes-encryption-plugin插件，客户端不解密nacos服务端返回的密文

### ISSUE THREAD

**Issue by MaxBill** [nacos-group/nacos-plugin#13]
客户端配置
![image](https://user-images.githubusercontent.com/16558525/170972325-7a5c9f2c-f971-4095-a795-92ac6a56cc6a.png)

数据源注入处
![image](https://user-images.githubusercontent.com/16558525/170973922-12ef4d6a-1841-4c57-ba2e-4948627c5622.png)

个人猜测是不是数据源注入发生在解密过程之前

**Comment by li-xiao-shuang** [comment]
> 客户端配置 ![image](https://user-images.githubusercontent.com/16558525/170972325-7a5c9f2c-f971-4095-a795-92ac6a56cc6a.png)
> 
> 数据源注入处 ![image](https://user-images.githubusercontent.com/16558525/170973922-12ef4d6a-1841-4c57-ba2e-4948627c5622.png)
> 
> 个人猜测是不是数据源注入发生在解密过程之前

客户端和服务端都依赖插件了嘛？

**Comment by MaxBill** [comment]
@li-xiao-shuang 

> > 客户端配置 ![image](https://user-images.githubusercontent.com/16558525/170972325-7a5c9f2c-f971-4095-a795-92ac6a56cc6a.png)
> > 数据源注入处 ![image](https://user-images.githubusercontent.com/16558525/170973922-12ef4d6a-1841-4c57-ba2e-4948627c5622.png)
> > 个人猜测是不是数据源注入发生在解密过程之前
> 
> 客户端和服务端都依赖插件了嘛？

是的，客户端和服务端都依赖了nacos-aes-encryption-plugin （1.0.0），服务端是2.1.0  ，客户端是nacos-config-spring-boot-starter  0.2.10

**Comment by MaxBill** [comment]
@li-xiao-shuang  感谢，我换到客户端0.2.11-beta版本好了，先关闭了
