### ISSUE TITLE
nacos-encryption-plugin

### ISSUE THREAD

**Issue by zzl14273119** [nacos-group/nacos-plugin#9]
nacos-encryption-plugin模块是不是在2.0.4的版本中还未发布，目前依赖不到

**Comment by li-xiao-shuang** [comment]
> nacos-encryption-plugin模块是不是在2.0.4的版本中还未发布，目前依赖不到

是的  会在下个版本发布

**Comment by zzl14273119** [comment]
好的，谢谢

**Comment by li-xiao-shuang** [comment]
> 好的，谢谢

可以期待下 ，最近应该有个大版本发布

**Comment by li-xiao-shuang** [comment]
> nacos-encryption-plugin模块是不是在2.0.4的版本中还未发布，目前依赖不到

[2.1.0-BETA](https://github.com/alibaba/nacos/releases/tag/2.1.0-BETA)  测试版本已经发布了  可是测试下
